# Generated by Django 3.1.2 on 2020-10-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.IntegerField(null=True),
        ),
    ]
